# Milestone 7

### a) Choose a column in your dataset to predict using some or all of the other columns.. This can either be a quantitative column to perform regression on, or a qualitative column to perform classification on.
### b) Prepare your data for machine learning:  split your data into training and testing data, and if necessary, create dummy variables or scale columns.
### c) Fit a model that we covered in class to your training data.   The models covered in class are linear regression, polynomial regression, decision trees, k-nearest neighbors, and logistic regression.
### d) Evaluate the fit of your model using your testing and training data.  You should use the appropriate methods for your model.
### e) Repeat steps (c) and (d) with at least two different parameters for your model.  For linear regression, you should use different subsets of the independent variables (for example, by dropping independent variables with high p-values).
### f) Post your code to GitHub.
### g) Describe what prediction model and parameters you tried on your project page, as well as how you evaluated the model/parameter combinations and the results of the evaluation (ex. pros and cons of this model/parameter combo).  Conclude with recommending which parameter to use with this model to get the best predictions for your data.
### Submit your GitHub account name and a link to yoru proejct page or the actual document if there is no link.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import seaborn as sns
import numpy as np

### a) Choose a column in your dataset to predict using some or all of the other columns.. This can either be a quantitative column to perform regression on, or a qualitative column to perform classification on.

In [5]:
sleep_data = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")
sleep_data.describe(include = "all")

Person ID Gender         Age Occupation  Sleep Duration  \
count   374.000000    374  374.000000        374      374.000000   
unique         NaN      2         NaN         11             NaN   
top            NaN   Male         NaN      Nurse             NaN   
freq           NaN    189         NaN         73             NaN   
mean    187.500000    NaN   42.184492        NaN        7.132086   
std     108.108742    NaN    8.673133        NaN        0.795657   
min       1.000000    NaN   27.000000        NaN        5.800000   
25%      94.250000    NaN   35.250000        NaN        6.400000   
50%     187.500000    NaN   43.000000        NaN        7.200000   
75%     280.750000    NaN   50.000000        NaN        7.800000   
max     374.000000    NaN   59.000000        NaN        8.500000   

        Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
count         374.000000               374.000000    374.000000          374   
unique               NaN                      NaN           NaN            4   
top                  NaN                      NaN           NaN       Normal   
freq                 NaN                      NaN           NaN          195   
mean            7.312834                59.171123      5.385027          NaN   
std             1.196956                20.830804      1.774526          NaN   
min             4.000000                30.000000      3.000000          NaN   
25%             6.000000                45.000000      4.000000          NaN   
50%             7.000000                60.000000      5.000000          NaN   
75%             8.000000                75.000000      7.000000          NaN   
max             9.000000                90.000000      8.000000          NaN   

       Blood Pressure  Heart Rate   Daily Steps Sleep Disorder  
count             374  374.000000    374.000000            155  
unique             25         NaN           NaN              2  
top            130/85         NaN           NaN    Sleep Apnea  
freq               99         NaN           NaN             78  
mean              NaN   70.165775   6816.844920            NaN  
std               NaN    4.135676   1617.915679            NaN  
min               NaN   65.000000   3000.000000            NaN  
25%               NaN   68.000000   5600.000000            NaN  
50%               NaN   70.000000   7000.000000            NaN  
75%               NaN   72.000000   8000.000000            NaN  
max               NaN   86.000000  10000.000000            NaN

### b) Prepare your data for machine learning: split your data into training and testing data, and if necessary, create dummy variables or scale columns.

In [7]:
sleep_data_2 = sleep_data[['Age', 'Heart Rate', 'Sleep Disorder']].copy()

In [8]:
sleep_data_2['Sleep Disorder'] = sleep_data_2['Sleep Disorder'].fillna('None')

In [9]:
sleep_data_2['Sleep Disorder'] = sleep_data_2['Sleep Disorder'].map({
    'None': 0,
    'Sleep Apnea': 1,
    'Insomnia': 2
})

In [10]:
sleep_data_2

Age  Heart Rate  Sleep Disorder
0     27          77               0
1     28          75               0
2     28          75               0
3     28          85               1
4     28          85               1
..   ...         ...             ...
369   59          68               1
370   59          68               1
371   59          68               1
372   59          68               1
373   59          68               1

[374 rows x 3 columns]

In [11]:
x = sleep_data_2[['Age', 'Heart Rate']]
y = sleep_data_2['Sleep Disorder']

### b) Prepare your data for machine learning: split your data into training and testing data, and if necessary, create dummy variables or scale columns.

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)


### d) Evaluate the fit of your model using your testing and training data. You should use the appropriate methods for your model.

In [15]:
tree_3 = DecisionTreeClassifier(max_depth = 3)
tree_3.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [16]:
y_test_pred_3 = tree_3.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_pred_3)

array([[43,  1,  1],
       [ 2, 14,  1],
       [ 5,  2,  6]])

In [18]:
from sklearn.metrics import accuracy_score

accuracy_3 = accuracy_score(y_test, y_test_pred_3)
print("Accuracy:", accuracy_3)

Accuracy: 0.84


### e) Repeat steps (c) and (d) with at least two different parameters for your model. For linear regression, you should use different subsets of the independent variables (for example, by dropping independent variables with high p-values).

### Decison Tree Depth 5

In [21]:
tree_5 = DecisionTreeClassifier(max_depth = 5)
tree_5.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5)

In [22]:
y_test_pred_5 = tree_5.predict(x_test)

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_pred_5)

array([[43,  1,  1],
       [ 2, 14,  1],
       [ 1,  1, 11]])

In [24]:
from sklearn.metrics import accuracy_score

accuracy_5 = accuracy_score(y_test, y_test_pred_5)
print("Accuracy:", accuracy_5)

Accuracy: 0.9066666666666666


### Decison Tree Depth 10

In [26]:
tree_10 = DecisionTreeClassifier(max_depth = 10)
tree_10.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10)

In [27]:
y_test_pred_10 = tree_10.predict(x_test)

In [28]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_pred_10)

array([[43,  1,  1],
       [ 2, 14,  1],
       [ 1,  1, 11]])

In [29]:
from sklearn.metrics import accuracy_score

accuracy_10 = accuracy_score(y_test, y_test_pred_10)
print("Accuracy:", accuracy_10)

Accuracy: 0.9066666666666666
