# Milestone 8: Model 2

### In this step, you will predict the same variable as in Milestone 7 but using a different machine learning model: 
### a) Fit a different model that the one used in Milestone 7 to your training data.  You must use a model covered in class (linear regression, polynomial regression, decision trees, k-nearest neighbors, logistic regression).
### b) Evaluate the fit of your 2nd model using your testing and training data.  You should use the appropriate methods for your model.
### c) Repeat steps (a) and (b) with at least two different parameters for your 2nd model.  For linear regression, you can use different subsets of the independent variables (for example, by dropping independent variables with high p-values).
### h) Compare the how well Model 1 (Milestone 7) and Model 2 (Milestone 8) preformed on your data, and make a final recommendation of which model to use to make the predictions.

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import seaborn as sns
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix

In [4]:
sleep_data = pd.read_csv("./Sleep_health_and_lifestyle_dataset.csv")
sleep_data.describe(include = "all")

Person ID Gender         Age Occupation  Sleep Duration  \
count   374.000000    374  374.000000        374      374.000000   
unique         NaN      2         NaN         11             NaN   
top            NaN   Male         NaN      Nurse             NaN   
freq           NaN    189         NaN         73             NaN   
mean    187.500000    NaN   42.184492        NaN        7.132086   
std     108.108742    NaN    8.673133        NaN        0.795657   
min       1.000000    NaN   27.000000        NaN        5.800000   
25%      94.250000    NaN   35.250000        NaN        6.400000   
50%     187.500000    NaN   43.000000        NaN        7.200000   
75%     280.750000    NaN   50.000000        NaN        7.800000   
max     374.000000    NaN   59.000000        NaN        8.500000   

        Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
count         374.000000               374.000000    374.000000          374   
unique               NaN                      NaN           NaN            4   
top                  NaN                      NaN           NaN       Normal   
freq                 NaN                      NaN           NaN          195   
mean            7.312834                59.171123      5.385027          NaN   
std             1.196956                20.830804      1.774526          NaN   
min             4.000000                30.000000      3.000000          NaN   
25%             6.000000                45.000000      4.000000          NaN   
50%             7.000000                60.000000      5.000000          NaN   
75%             8.000000                75.000000      7.000000          NaN   
max             9.000000                90.000000      8.000000          NaN   

       Blood Pressure  Heart Rate   Daily Steps Sleep Disorder  
count             374  374.000000    374.000000            155  
unique             25         NaN           NaN              2  
top            130/85         NaN           NaN    Sleep Apnea  
freq               99         NaN           NaN             78  
mean              NaN   70.165775   6816.844920            NaN  
std               NaN    4.135676   1617.915679            NaN  
min               NaN   65.000000   3000.000000            NaN  
25%               NaN   68.000000   5600.000000            NaN  
50%               NaN   70.000000   7000.000000            NaN  
75%               NaN   72.000000   8000.000000            NaN  
max               NaN   86.000000  10000.000000            NaN

In [5]:
sleep_data_2 = sleep_data[['Age', 'Heart Rate', 'Sleep Disorder']].copy()

In [6]:
sleep_data_2['Sleep Disorder'] = sleep_data_2['Sleep Disorder'].fillna('None')

In [7]:
sleep_data_2['Sleep Disorder'] = sleep_data_2['Sleep Disorder'].map({
    'None': 0,
    'Sleep Apnea': 1,
    'Insomnia': 2
})

In [8]:
sleep_data_2

Age  Heart Rate  Sleep Disorder
0     27          77               0
1     28          75               0
2     28          75               0
3     28          85               1
4     28          85               1
..   ...         ...             ...
369   59          68               1
370   59          68               1
371   59          68               1
372   59          68               1
373   59          68               1

[374 rows x 3 columns]

In [9]:
x = sleep_data_2[['Age', 'Heart Rate']]
y = sleep_data_2['Sleep Disorder']

### b) Prepare your data for machine learning: split your data into training and testing data, and if necessary, create dummy variables or scale columns.

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

### d) Evaluate the fit of your model using your testing and training data. You should use the appropriate methods for your model.

### Random Forest Classifier

In [14]:
rf_50 = RandomForestClassifier(n_estimators = 10, max_depth = 2)
rf_50.fit(x_train, y_train)

RandomForestClassifier(max_depth=2, n_estimators=10)

In [15]:
y_test_pred_rf_50 = rf_50.predict(x_test)

In [16]:
confusion_matrix(y_test,y_test_pred_rf_50)

array([[47,  0,  0],
       [ 8,  6,  4],
       [ 6,  0,  4]])

In [49]:
from sklearn.metrics import accuracy_score

rf_50_accuracy = accuracy_score(y_test, y_test_pred_rf_50)
print("Accuracy:", rf_50_accuracy)

Accuracy: 0.76


### e) Repeat steps (c) and (d) with at least two different parameters for your model. For linear regression, you should use different subsets of the independent variables (for example, by dropping independent variables with high p-values).

### Random Forest Classifier Max Depth 100

In [20]:
rf_100 = RandomForestClassifier(n_estimators = 500, max_depth = 100)
rf_100.fit(x_train, y_train)

RandomForestClassifier(max_depth=100, n_estimators=500)

In [21]:
y_test_pred_rf_100 = rf_100.predict(x_test)

In [22]:
confusion_matrix(y_test,y_test_pred_rf_100)

array([[45,  1,  1],
       [ 1, 14,  3],
       [ 1,  1,  8]])

In [23]:
from sklearn.metrics import accuracy_score

rf_100_accuracy = accuracy_score(y_test, y_test_pred_rf_50)
print("Accuracy:", rf_100_accuracy)

Accuracy: 0.76


### Random Forest Classifier Max Depth 300

In [25]:
rf_300 = RandomForestClassifier(n_estimators = 1000, max_depth = 500)
rf_300.fit(x_train, y_train)

RandomForestClassifier(max_depth=500, n_estimators=1000)

In [26]:
y_test_pred_rf_300 = rf_300.predict(x_test)

In [27]:
confusion_matrix(y_test,y_test_pred_rf_300)

array([[45,  1,  1],
       [ 1, 14,  3],
       [ 1,  1,  8]])

In [28]:
from sklearn.metrics import accuracy_score

rf_300_accuracy = accuracy_score(y_test, y_test_pred_rf_300)
print("Accuracy:", rf_300_accuracy)

Accuracy: 0.8933333333333333
